# Generated by Django 3.2.9 on 2022-05-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(default='M', max_length=1),
            preserve_default=False,
        ),
    ]
