# Generated by Django 3.2.9 on 2022-05-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicamento',
            fields=[
                ('id_stock', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_drug', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('max_cant', models.IntegerField(blank=True)),
                ('laboratorio', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
