# Generated by Django 3.2.9 on 2022-05-30 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220520_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='id_stock',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
