# Generated by Django 3.2.4 on 2021-07-07 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='autor',
            fields=[
                ('id_autor', models.IntegerField(primary_key=True, serialize=False, verbose_name='id del autor')),
                ('nombrea', models.CharField(max_length=50, verbose_name='nombre del autor')),
                ('descripcion', models.CharField(max_length=250, verbose_name='descripcion del autor')),
                ('imagen', models.ImageField(upload_to='', verbose_name='imagen autor')),
            ],
        ),
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de la categoria')),
                ('nombrec', models.CharField(max_length=25, verbose_name='nombre de la categoria')),
                ('imagen', models.ImageField(upload_to='', verbose_name='imagen de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id_user', models.IntegerField(primary_key=True, serialize=False, verbose_name='id del usuario')),
                ('nickname', models.CharField(max_length=30, verbose_name='nombre de usuario')),
                ('correo', models.CharField(max_length=320, verbose_name='correo del usuario')),
                ('contraseña', models.CharField(max_length=25, verbose_name='contraseña del usuario')),
                ('imagen', models.ImageField(upload_to='', verbose_name='imagen del usuario')),
            ],
        ),
        migrations.CreateModel(
            name='obras',
            fields=[
                ('id_obra', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de la obra')),
                ('nombreo', models.CharField(max_length=30, verbose_name='nombre de la obra')),
                ('descripcion', models.CharField(max_length=250, verbose_name='descripcion de la obra')),
                ('imagen', models.ImageField(upload_to='', verbose_name='imagen de la obra')),
                ('precio', models.IntegerField(verbose_name='precio de la obra')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.autor')),
            ],
        ),
        migrations.AddField(
            model_name='autor',
            name='categorias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categorias'),
        ),
    ]
