# Generated by Django 3.2.4 on 2021-07-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='imagen',
            field=models.CharField(max_length=2000, verbose_name='imagen autor'),
        ),
    ]
