# Generated by Django 3.2.4 on 2021-07-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_autor_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='descripcion',
            field=models.CharField(max_length=2500, verbose_name='descripcion del autor'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='imagen',
            field=models.CharField(max_length=1000, verbose_name='imagen autor'),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='imagen',
            field=models.CharField(max_length=1000, verbose_name='imagen categoria'),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='nombrec',
            field=models.CharField(max_length=50, verbose_name='nombre de la categoria'),
        ),
        migrations.AlterField(
            model_name='obras',
            name='descripcion',
            field=models.CharField(max_length=2500, verbose_name='descripcion de la obra'),
        ),
        migrations.AlterField(
            model_name='obras',
            name='imagen',
            field=models.CharField(max_length=1000, verbose_name='imagen obra'),
        ),
        migrations.AlterField(
            model_name='obras',
            name='nombreo',
            field=models.CharField(max_length=50, verbose_name='nombre de la obra'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='imagen',
            field=models.CharField(max_length=1000, verbose_name='imagen usuario'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nickname',
            field=models.CharField(max_length=50, verbose_name='nombre de usuario'),
        ),
    ]
