# Generated by Django 3.2.9 on 2022-05-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prescripcion',
            fields=[
                ('id_presc', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_doc', models.CharField(max_length=50)),
                ('nom_pac', models.CharField(max_length=50)),
                ('rut_pac', models.CharField(max_length=10)),
                ('receta', models.CharField(max_length=500)),
            ],
        ),
    ]
